import { useState, type ReactNode } from 'react';
import { ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays, ChevronDown, CircleHelp, Clock3, Download, FileText, ShieldAlert, ShieldCheck, ShieldX } from 'lucide-react';
import { trend } from '../data';
import { formatNumber } from '../lib/format';

export function AnalyticsPage() {
  const [range, setRange] = useState('7 days');
  const total = trend.reduce((sum, item) => sum + item.allow + item.flag + item.block, 0);
  const maxDay = Math.max(...trend.map((item) => item.allow + item.flag + item.block));
  const distribution = [
    { label: '0–20%', value: 41, color: 'dist-violet' },
    { label: '20–40%', value: 24, color: 'dist-blue' },
    { label: '40–60%', value: 21, color: 'dist-slate' },
    { label: '60–80%', value: 10, color: 'dist-amber' },
    { label: '80–100%', value: 4, color: 'dist-rose' },
  ];
  return <div className="page-content">
    <div className="page-heading"><div><div className="eyebrow">MEASURE <span className="eyebrow-separator">/</span> WORKSPACE PERFORMANCE</div><h1>Analytics</h1><p>Understand decision volume and detector signals across your integrations.</p></div><div className="heading-actions"><div className="select-wrap analytics-range"><CalendarDays size={14} /><select value={range} onChange={(event) => setRange(event.target.value)}><option>7 days</option><option>30 days</option><option>90 days</option></select><ChevronDown size={13} /></div><button className="button button-secondary" onClick={() => window.print()}><Download size={14} />Export report</button></div></div>
    <div className="analytics-kpi-grid"><Kpi title="Evaluations" value={range === '7 days' ? formatNumber(total) : formatNumber(total * (range === '30 days' ? 4 : 12))} suffix="" change="12.8%" icon={<FileText size={17} />} tone="violet" /><Kpi title="AI-likely signal" value="14.0" suffix="%" change="1.6%" icon={<ShieldAlert size={17} />} tone="amber" negative /><Kpi title="Human review rate" value="11.2" suffix="%" change="0.8%" icon={<Clock3 size={17} />} tone="blue" /><Kpi title="Review overturns" value="6.4" suffix="%" change="2.1%" icon={<ShieldCheck size={17} />} tone="green" negative /></div>
    <div className="analytics-grid-main">
      <section className="card analytics-volume-card"><div className="card-header"><div><h2>Evaluations over time</h2><p>Daily volume by moderation outcome · {range}</p></div><button className="subtle-icon" title="Stacked volume chart"><CircleHelp size={15} /></button></div><div className="stacked-chart"><div className="stacked-y-axis"><span>350</span><span>250</span><span>150</span><span>50</span><span>0</span></div><div className="stacked-plot"><div className="stacked-grid-lines"><i /><i /><i /><i /><i /></div><div className="stacked-bars">{trend.map((item) => { const dayTotal = item.allow + item.flag + item.block; const scale = dayTotal / maxDay; return <div className="stacked-bar-column" key={item.day}><div className="stacked-bar" style={{ height: `${Math.max(38, scale * 205)}px` }}><span className="bar-allow" style={{ height: `${(item.allow / dayTotal) * 100}%` }} /><span className="bar-flag" style={{ height: `${(item.flag / dayTotal) * 100}%` }} /><span className="bar-block" style={{ height: `${(item.block / dayTotal) * 100}%` }} /></div><span className="bar-day-label">{item.day}</span></div>; })}</div></div></div><div className="chart-footer-legend"><span><i className="chart-legend-allow" />ALLOW</span><span><i className="chart-legend-flag" />FLAG</span><span><i className="chart-legend-block" />BLOCK</span><span className="chart-footer-total">{formatNumber(total)} total events</span></div></section>
      <section className="card likelihood-card"><div className="card-header"><div><h2>Likelihood distribution</h2><p>Score ranges for analyzed content</p></div><button className="subtle-icon" title="Illustrative distribution"><CircleHelp size={15} /></button></div><div className="likelihood-total"><strong>2,846</strong><span>analyses this period</span></div><div className="distribution-bars">{distribution.map((item) => <div className="distribution-row" key={item.label}><span>{item.label}</span><div className="distribution-track"><i className={item.color} style={{ width: `${(item.value / 45) * 100}%` }} /></div><b>{item.value}%</b></div>)}</div><div className="likelihood-insight"><span className="insight-bulb">✦</span><p><b>14.0% high-likelihood</b> signals reached or exceeded the review threshold in the selected period.</p></div></section>
    </div>
    <div className="analytics-grid-bottom"><section className="card app-performance-card"><div className="card-header"><div><h2>Application performance</h2><p>Usage and outcomes by integration</p></div><button className="text-link">View apps <ArrowRight size={13} /></button></div><div className="app-performance-table"><div className="performance-head"><span>APPLICATION</span><span>ANALYSES</span><span>FLAG RATE</span><span>BLOCK RATE</span><span>MEDIAN LATENCY</span></div>{[['Student Portal','12,840','12.1%','1.4%','178 ms'],['LMS','8,662','10.8%','1.1%','164 ms'],['Assignment Checker','3,920','15.6%','2.0%','202 ms'],['Research Repository','1,840','8.2%','0.7%','191 ms']].map((row) => <div className="performance-row" key={row[0]}><span><i className="performance-app-dot" />{row[0]}</span><b>{row[1]}</b><span>{row[2]}</span><span>{row[3]}</span><span className="latency-value">{row[4]}</span></div>)}</div></section><section className="card model-performance-card"><div className="card-header"><div><h2>Model performance</h2><p>Operational metrics</p></div><span className="health-status"><i />LIVE</span></div><div className="model-metric-row"><span><span className="model-metric-icon"><Clock3 size={15} /></span>Median inference latency</span><b>184 <small>ms</small></b></div><div className="model-metric-row"><span><span className="model-metric-icon"><ShieldCheck size={15} /></span>API success rate</span><b>99.6<small>%</small></b></div><div className="model-metric-row"><span><span className="model-metric-icon"><ShieldX size={15} /></span>Analysis failures</span><b>0.4<small>%</small></b></div><div className="analytics-caveat"><CircleHelp size={14} /><span>Sandbox sample metrics. Real-world accuracy needs a held-out, representative dataset.</span></div></section></div>
    <div className="analytics-note"><ShieldCheck size={15} /><span><b>Metrics need context.</b> AI-detection analytics are not ground truth. For academic evaluation, use labeled test data and report false-positive and false-negative rates.</span><button className="text-link">Evaluation guide <ArrowRight size={13} /></button></div>
  </div>;
}

function Kpi({ title, value, suffix, change, icon, tone, negative = false }: { title: string; value: string; suffix: string; change: string; icon: ReactNode; tone: string; negative?: boolean }) {
  return <div className={`card analytics-kpi kpi-${tone}`}><div className="analytics-kpi-top"><span>{title}</span><span className="analytics-kpi-icon">{icon}</span></div><div className="analytics-kpi-value"><strong>{value}</strong><small>{suffix}</small></div><div className={`analytics-kpi-change ${negative ? 'change-negative' : ''}`}>{negative ? <ArrowDownRight size={13} /> : <ArrowUpRight size={13} />}{change}<span> vs prev. period</span></div></div>;
}
